Vagrant.configure('2') do |config|
  config.vm.box = 'centos/6'
  config.vm.define :spring do |node|
    node.vm.hostname = 'spring-boot'
    node.vm.network :private_network,
                    ip: '192.168.88.30'
    node.vm.network :forwarded_port,
                    guest: 80,
                    host: 8080,
                    auto_correct: true
  end
  config.vm.provision :shell,
                      path: 'bootstrap.sh'
end